# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec544c55928a7dd737b460cf2ebae90b3ebe657cdabea93ece7a20f44228df237cba63abf89047ab647b8628202503aeb5e97cb2816729910f0ebd10f4222924

test:
  secret_key_base: 42f10fb1e8d85bd666bde648bc1f3fd310f3da6bb28ae450cd89f36204893c14ede4868e4ddff7f85f6a8cda0e41693b6cfdf5b7fb956081ee781b900e9530f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
